### ISSUE TITLE
Disables configuration of app client settings

### ISSUE THREAD

**Issue by nirLumigo** [jmaleonard/serverless-cognito-add-custom-attributes#11]
Hi,
When using the plugin, it's not possible to set the configuration of "app client settings" for `AWS::Cognito::UserPoolClient` (e.g: `CallbackURLs`, `AllowedOAuthFlows` etc.)
There aren't error messages during deployment, but all of the fields are cleared instead of being filled:
![image](https://user-images.githubusercontent.com/49228804/77247867-cf015f80-6c3d-11ea-9240-90cb6c278599.png)

The only message which might be a warning is: `Supplied attributes already exist in pool`.

After removing `CognitoAddCustomAttributes` section from the serverless.yml, it worked as expected and "app client settings" page wasn't empty.

The entire output:
```
Serverless: CognitoAddCustomAttributesPlugin: Start
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolId: us-west-2_v9kjJEzYT
Serverless: CognitoAddCustomAttributesPlugin: End
Serverless: CognitoAddCustomAttributesPlugin: Found userPoolClientId: 5hb9gt3h0u6u7l080eg8gj11os
Serverless: Removing old service artifacts from S3...
Serverless: Run the "serverless" command to setup monitoring, troubleshooting and testing.
Serverless: CognitoAddCustomAttributesPlugin: Supplied attributes already exist in pool
Serverless: CognitoAddCustomAttributesPlugin: Enabling client to read from 3 new attribute(s): custom:customer,custom:customer-name,custom:role
Serverless: CognitoAddCustomAttributesPlugin: Enabling client to write to 3 new attribute(s): custom:customer,custom:customer-name,custom:role
Serverless: CognitoAddCustomAttributesPlugin: Successfully updated client
```

**Comment by NivardoX** [comment]
Same problem here. Any updates?

**Comment by jmaleonard** [comment]
Will investigate

**Comment by jobarbosa** [comment]
Same problem for me. After adding new custom cognito attributes and deploy, the app client settings gets reset.
Any news?

**Comment by michaelduminy** [comment]
@nirLumigo @NivardoX @jobarbosa 
I've pushed a potential fix, but haven't published anything because I have not had the chance to test this (NB)

From what I can tell the AWS Cognito API changed at some point. Previously you'd be able to pass up each different property of a UserPoolClient and only those properties were being updated. Now it seems like it defaults all the properties you don't pass up.

I will try get this tested sometime but if you are in a hurry please feel free to test the change locally (just pull down the repo).

**Comment by fuzzy28** [comment]
@mikeduminy how to get the release with the fix?, I'm badly need the fix now :(

**Comment by mikeduminy** [comment]
@fuzzy28 I'm unable to support this repo any more so I've transferred it to @jmaleonard

**Comment by madox2** [comment]
I have tested and reviewed latest code changes on the master branch, it all looks good. Please, release to the npm
